### ISSUE TITLE
Move Responsibility for Storing file on Minio Here

### ISSUE THREAD

**Issue by VincenzoFerme** [benchflow/test-orchestrator#4]
Move Responsibility for Storing file on Minio Here from the Experiments-Manager

**Comment by simonedavico** [comment]
I think there is nothing to move. The implemented components only store their own files on Minio.
The only exception is the `models` folder, that is uploaded at test level from the `experiments-manager` since we don't have a `test-orchestrator` yet.

**Comment by VincenzoFerme** [comment]
Ok then the `models` folder should be moved, as well as `test` level files that are the artefact sentry the user. Then the other components will save their own version of that artefacts.

**Comment by VincenzoFerme** [comment]
This issue was moved to benchflow/benchflow#232
